import type { RoadmapItem } from "./types";

// Order matters: within a horizon, the first item is the next one to pick up.
export const items: RoadmapItem[] = [
  {
    id: "rescue",
    theme: "back",
    horizon: "now",
    segments: ["lifestyle", "coached"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_adherence_prd" },
    evidence: "prd",
    phase: "A",
  },
  {
    id: "comeback",
    theme: "back",
    horizon: "now",
    segments: ["lifestyle", "coached"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_adherence_prd" },
    evidence: "prd",
    phase: "A",
  },
  {
    id: "nudge-engine",
    theme: "back",
    horizon: "now",
    segments: ["lifestyle", "coached"],
    kind: "feature",
    platforms: ["api", "ios"],
    effort: "m",
    source: { key: "source_production_gap" },
    evidence: "production",
    phase: "A",
  },
  {
    id: "checkin-ritual",
    theme: "progress",
    horizon: "now",
    segments: ["lifestyle", "coached"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_production_data" },
    evidence: "production",
    phase: "B",
  },
  {
    id: "weekly-recap",
    theme: "progress",
    horizon: "now",
    segments: ["lifestyle", "coached"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_launch_gate" },
    evidence: "production",
    phase: "B",
  },
  {
    id: "first-week",
    theme: "start",
    horizon: "now",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_production_data" },
    evidence: "production",
  },
  {
    id: "health-steps-verify",
    theme: "data",
    horizon: "now",
    segments: ["lifestyle"],
    kind: "fix",
    platforms: ["ios", "api"],
    effort: "s",
    source: { key: "source_device_check" },
    evidence: "device",
  },
  {
    id: "catalog-saudi",
    theme: "data",
    horizon: "now",
    segments: ["lifestyle"],
    kind: "content",
    platforms: ["api", "data"],
    effort: "m",
    source: { key: "source_macrofactor", votes: 3974 },
    evidence: "demand",
  },
  {
    id: "analytics-loop",
    theme: "data",
    horizon: "now",
    segments: ["coach"],
    kind: "infra",
    platforms: ["api", "web"],
    effort: "s",
    source: { key: "source_open_pr_31" },
    evidence: "production",
  },
  {
    id: "meal-repeat",
    theme: "loop",
    horizon: "next",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_macrofactor", votes: 5777 },
    evidence: "demand",
  },
  {
    id: "meal-suggest",
    theme: "loop",
    horizon: "next",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_macrofactor", votes: 5136 },
    evidence: "demand",
  },
  {
    id: "weighin-nudge",
    theme: "loop",
    horizon: "next",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "s",
    source: { key: "source_macrofactor", votes: 6649 },
    evidence: "demand",
  },
  {
    id: "water",
    theme: "loop",
    horizon: "next",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_macrofactor", votes: 5635 },
    evidence: "demand",
  },
  {
    id: "arabic-quality",
    theme: "data",
    horizon: "next",
    segments: ["lifestyle", "coached", "coach"],
    kind: "polish",
    platforms: ["ios", "web", "dashboard"],
    effort: "l",
    source: { key: "source_product_call" },
    evidence: "policy",
  },
  {
    id: "share-card",
    theme: "progress",
    horizon: "next",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_adherence_prd" },
    evidence: "prd",
    phase: "B",
  },
  {
    id: "measurements",
    theme: "progress",
    horizon: "next",
    segments: ["lifestyle", "coached"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_adherence_prd" },
    evidence: "prd",
    phase: "C",
  },
  {
    id: "streaks",
    theme: "progress",
    horizon: "next",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_adherence_prd" },
    evidence: "prd",
    phase: "C",
  },
  {
    id: "coach-visibility",
    theme: "coach",
    horizon: "next",
    segments: ["coached", "coach"],
    kind: "feature",
    platforms: ["dashboard", "api"],
    effort: "m",
    source: { key: "source_adherence_prd_cross_cutting" },
    evidence: "prd",
  },
  {
    id: "training-videos",
    theme: "loop",
    horizon: "next",
    segments: ["lifestyle"],
    kind: "polish",
    platforms: ["ios"],
    effort: "m",
    source: { key: "source_device_check" },
    evidence: "device",
  },
  {
    id: "step-target-policy",
    theme: "start",
    horizon: "next",
    segments: ["lifestyle"],
    kind: "research",
    platforms: ["api", "data"],
    effort: "s",
    source: { key: "source_open_decision" },
    evidence: "policy",
  },
  {
    id: "ramadan",
    theme: "loop",
    horizon: "later",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "l",
    source: { key: "source_product_call_feb_2027" },
    evidence: "policy",
  },
  {
    id: "meal-plan-week",
    theme: "loop",
    horizon: "later",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "l",
    source: { key: "source_macrofactor", votes: 6659 },
    evidence: "demand",
  },
  {
    id: "sleep-context",
    theme: "data",
    horizon: "later",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_macrofactor", votes: 14155 },
    evidence: "demand",
  },
  {
    id: "widgets",
    theme: "loop",
    horizon: "later",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios"],
    effort: "m",
    source: { key: "source_macrofactor", votes: 2485 },
    evidence: "demand",
  },
  {
    id: "referral",
    theme: "progress",
    horizon: "later",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_adherence_prd" },
    evidence: "prd",
    phase: "D",
  },
  {
    id: "fasting-window",
    theme: "loop",
    horizon: "later",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_macrofactor", votes: 3896 },
    evidence: "demand",
  },
  {
    id: "cycle-overlay",
    theme: "progress",
    horizon: "later",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_macrofactor", votes: 3635 },
    evidence: "demand",
  },
  {
    id: "web-client",
    theme: "data",
    horizon: "parked",
    segments: ["advanced"],
    kind: "feature",
    platforms: ["web"],
    effort: "l",
    source: { key: "source_macrofactor", votes: 5281 },
    evidence: "demand",
    parked: true,
  },
  {
    id: "alcohol-calc",
    theme: "loop",
    horizon: "parked",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios"],
    effort: "s",
    source: { key: "source_macrofactor", votes: 4773 },
    evidence: "demand",
    parked: true,
  },
  {
    id: "micronutrients",
    theme: "loop",
    horizon: "parked",
    segments: ["advanced"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_macrofactor", votes: 1202 },
    evidence: "demand",
    parked: true,
  },
  {
    id: "net-carbs",
    theme: "loop",
    horizon: "parked",
    segments: ["advanced"],
    kind: "feature",
    platforms: ["api"],
    effort: "s",
    source: { key: "source_macrofactor", votes: 1339 },
    evidence: "demand",
    parked: true,
  },
  {
    id: "wearables",
    theme: "data",
    horizon: "parked",
    segments: ["advanced"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "l",
    source: { key: "source_product_call" },
    evidence: "policy",
    parked: true,
  },
  {
    id: "poop-tracker",
    theme: "loop",
    horizon: "parked",
    segments: ["lifestyle"],
    kind: "feature",
    platforms: ["ios", "api"],
    effort: "m",
    source: { key: "source_macrofactor", votes: 4421 },
    evidence: "demand",
    parked: true,
  },
  {
    id: "watch-app",
    theme: "data",
    horizon: "parked",
    segments: ["advanced"],
    kind: "feature",
    platforms: ["ios"],
    effort: "l",
    source: { key: "source_macrofactor", votes: 1964 },
    evidence: "demand",
    parked: true,
  },
  {
    id: "family-plan",
    theme: "coach",
    horizon: "parked",
    segments: ["coach"],
    kind: "feature",
    platforms: ["api", "web"],
    effort: "l",
    source: { key: "source_product_call" },
    evidence: "policy",
    parked: true,
  },
];
